# Generated by Django 4.0.4 on 2023-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesection',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='business_call_to_action',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_cta_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
