# Generated by Django 4.0.4 on 2023-07-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
