# Generated by Django 4.0.4 on 2023-07-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_product_payment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
