# Generated by Django 4.0.4 on 2023-07-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_business_business_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.product'),
        ),
    ]
