# Generated by Django 4.0.4 on 2023-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
