# Generated by Django 4.0.4 on 2023-07-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_media_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_media',
            name='video',
            field=models.FileField(blank=True, default='/static/images/nva.png', null=True, upload_to='media'),
        ),
    ]
