# Generated by Django 4.0.4 on 2023-08-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cta_click',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
