# Generated by Django 4.0.4 on 2023-08-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_cta_click'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_payment_link',
            new_name='product_redirect_url',
        ),
    ]
