# Generated by Django 4.0.4 on 2023-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_product_payment_link_product_product_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
