# Generated by Django 4.0.4 on 2023-08-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_status_product_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='status',
            field=models.CharField(choices=[('Hidden', 'Hidden'), ('Active', 'Active')], default='Active', max_length=10, null=True),
        ),
    ]
