# Generated by Django 4.0.4 on 2023-08-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_product_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_terms',
            field=models.TextField(null=True),
        ),
    ]
